channels:
  - pytorch
  - conda-forge
  - defaults
  - pyg
dependencies:
  - pip=21.3.1
  - pyg
  - python=3.9.9
  - cpuonly
  - pytorch=1.11.0
  - pip:
      - torch-householder==1.0.1
      - tqdm==4.62.3
      - pytest==6.2.5
      - wandb==0.13.1
      - torchdiffeq==0.2.2
      - networkx==2.6.3
      - POT
name: nsd_cpu